services:
  - type: web
    name: renderfs
    env: docker
    plan: free
    region: singapore
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: renderfs-db
          property: connectionString
        description: "PostgreSQL database connection string"
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: SUPERUSER_EMAIL
        value: jomonsolinap@gmail.com
        description: "The email of the first superuser to be created. This will be used for login."
        sync: false
      - key: SUPERUSER_PASS
        value: @$Ss07271991
        description: "The password of the first superuser. Update this for production."
        sync: false
      - key: WORKERS
        value: 4
      - key: CHANNEL_CAPACITY
        value: 32
      - key: TELEGRAM_API_BASE_URL
        value: https://api.telegram.org
      - key: ACCESS_TOKEN_EXPIRE_IN_SECS
        value: 1800
      - key: REFRESH_TOKEN_EXPIRE_IN_DAYS
        value: 14

databases:
  - name: renderfs-db
    plan: free
    postgresMajorVersion: 15
