services:
  - type: web
    name: pentaract
    env: docker
    plan: free # or whatever plan the user prefers
    region: frankfurt # default region
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: pentaract-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: SUPERUSER_EMAIL
        sync: false
      - key: SUPERUSER_PASS
        sync: false
      - key: WORKERS
        value: 4
      - key: CHANNEL_CAPACITY
        value: 32
      - key: TELEGRAM_API_BASE_URL
        value: https://api.telegram.org
      - key: ACCESS_TOKEN_EXPIRE_IN_SECS
        value: 1800
      - key: REFRESH_TOKEN_EXPIRE_IN_DAYS
        value: 14

databases:
  - name: pentaract-db
    plan: free
    postgresMajorVersion: 15
